#!/usr/bin/env python3
"""
Build coherent test fixtures from real production data.

Strategy:
1. Pick 5 JM rows → gives us 5 adamlink addresses + WGS84 points
2. Find LP points (in the LPS TTL) whose schema:geoWithin references those addresses
3. Stream beeldbank.csv, pick rows whose `address` is at one of our LPs
4. If few matches, add LP points covering addresses seen in beeldbank
5. Extract the matching LP blocks (lps.ttl) and address blocks (adressen.ttl) from the source TTLs

lps.ttl and adressen.ttl are generated here, not hand-edited: extract_lps_ttl() and
extract_adressen_ttl() lift the real blocks for the in-scope ids out of the source
TTLs verbatim.
"""
import csv
import re
import sys

SRC = "/home/m/Documents/projects/2026/atm-postgis-integration/data"
DST = "/home/m/Documents/projects/2024/amsterdam_time_machine/packages/db/src/__tests__/fixtures"
ADRESSEN_TTL = f"{SRC}/20240311-adressen.ttl"
LPS_TTL = f"{SRC}/20230920-lps.ttl"

csv.field_size_limit(sys.maxsize)

ADAMLINK_PREFIX = "https://adamlink.nl/geo/address/"

ADRESSEN_TTL_HEADER = """\
# Test fixture: a real subset of 20240311-adressen.ttl (Adamlink address observations).
#
# Each aladr: subject is one dated address observation that self-links to its LP
# point via schema:geoContains; the adressen ingestion turns each into a place_historical_name
# row (id = the aladr URI, place_id = the allp URI it geoContains, source = the albr label).
#
# Coverage: one block per registry id referenced by the lps.ttl fixture, plus the
# albr source documents those blocks cite. Regenerated by build.py — do not edit by
# hand (edit the build script instead).
"""

LPS_TTL_HEADER = """\
# Test fixture: a real subset of 20230920-lps.ttl (Adamlink linked points / LP geometry).
#
# Each allp: subject is one LP point; the lps ingestion creates a `place` row
# (id = the allp URI, type = address) from the allp URI + geo:asWKT geometry (WGS84,
# reprojected to RD on insert). The schema:geoWithin links (addresses, BAG building)
# are not used by the ingestion. Regenerated by build.py — do not edit by hand.
"""


def extract_adressen_ttl(all_addrs, src_ttl=ADRESSEN_TTL):
    """Build the adressen.ttl fixture by lifting real blocks out of the source TTL.

    Streams the (~100MB) TTL once, keeping only the aladr blocks we want plus every
    albr source block (a handful, all near the top). Blocks are copied verbatim — a
    block runs from a column-0 subject line to the line that ends the statement with
    '.'. We then emit the header, the prefixes those blocks reference, the cited
    source docs, and the address blocks (both sorted for a stable diff).
    """
    wanted = {f"aladr:{a}" for a in all_addrs}
    prefixes = {}   # name -> full "@prefix ..." line
    kept = {}       # subject -> [lines]
    subj = None
    lines = None
    keeping = False

    with open(src_ttl) as f:
        for raw in f:
            line = raw.rstrip("\n")
            if subj is None:
                m = re.match(r"@prefix\s+(\w+):", line)
                if m:
                    prefixes[m.group(1)] = line
                    continue
                if not line or line[0].isspace() or line.startswith("#"):
                    continue
                subj = line.split()[0]
                keeping = subj.startswith("albr:") or subj in wanted
                lines = [line] if keeping else None
                if line.rstrip().endswith("."):
                    if keeping:
                        kept[subj] = lines
                    subj = None
            else:
                if keeping:
                    lines.append(line)
                if line.rstrip().endswith("."):
                    if keeping:
                        kept[subj] = lines
                    subj = None

    # Keep only the source docs actually cited by the addresses we extracted.
    cited = set()
    for s, ls in kept.items():
        if s.startswith("aladr:"):
            for l in ls:
                cited.update(re.findall(r"albr:\w+", l))
    blocks = sorted(s for s in kept if s.startswith("albr:") and s in cited)
    blocks += sorted(s for s in kept if s.startswith("aladr:"))

    used = set()
    for s in blocks:
        for l in kept[s]:
            used.update(re.findall(r"(?<![<\w])(\w+):", l))
    prefix_block = "\n".join(prefixes[p] for p in prefixes if p in used)
    body = "\n\n".join("\n".join(kept[s]) for s in blocks)
    return f"{ADRESSEN_TTL_HEADER}{prefix_block}\n\n{body}\n"


def load_lps_ttl(src_ttl=LPS_TTL):
    """Parse the LPS TTL into {lp_id: aladr-id set}, {lp_id: verbatim block lines}, prefixes.

    Each allp: subject is a flat block (geo:asWKT directly on it). We record the
    addresses it covers (schema:geoWithin aladr:…) so the fixture's LP set and its
    address set stay in lockstep, and keep the block verbatim for emission.
    """
    lp_addrs, lp_blocks, prefixes = {}, {}, {}
    subj = lp_id = lines = addrs = None
    with open(src_ttl) as f:
        for raw in f:
            line = raw.rstrip("\n")
            if subj is None:
                m = re.match(r"@prefix\s+(\w+):", line)
                if m:
                    prefixes[m.group(1)] = line
                    continue
                if not line or line[0].isspace() or line.startswith("#"):
                    continue
                subj = line.split()[0]
                lp_id = subj[len("allp:"):] if subj.startswith("allp:") else None
                lines = [line]
                addrs = set(re.findall(r"aladr:(\w+)", line))
                if line.rstrip().endswith("."):
                    if lp_id:
                        lp_blocks[lp_id], lp_addrs[lp_id] = lines, addrs
                    subj = None
            else:
                lines.append(line)
                addrs.update(re.findall(r"aladr:(\w+)", line))
                if line.rstrip().endswith("."):
                    if lp_id:
                        lp_blocks[lp_id], lp_addrs[lp_id] = lines, addrs
                    subj = None
    return lp_addrs, lp_blocks, prefixes


def extract_lps_ttl(lp_ids, lp_blocks, prefixes):
    """Emit the lps.ttl fixture: header + referenced prefixes + the selected allp blocks (sorted)."""
    blocks = sorted((lp for lp in lp_ids if lp in lp_blocks), key=int)
    used = set()
    for lp in blocks:
        for l in lp_blocks[lp]:
            used.update(re.findall(r"(?<![<\w])(\w+):", l))
    prefix_block = "\n".join(prefixes[p] for p in prefixes if p in used)
    body = "\n\n".join("\n".join(lp_blocks[lp]) for lp in blocks)
    return f"{LPS_TTL_HEADER}{prefix_block}\n\n{body}\n"


# Step 1: Take first 5 JM rows
print("1. Sampling 5 JM rows...")
jm_rows = []
with open(f"{SRC}/results_jm.csv") as f:
    reader = csv.DictReader(f)
    for i, row in enumerate(reader):
        if i >= 5:
            break
        jm_rows.append(row)

jm_addrs = [r['address'].replace(ADAMLINK_PREFIX, '') for r in jm_rows]
print(f"   JM addresses: {jm_addrs}")

# Step 2: Load the LPS TTL, find LPs whose geoWithin references a JM address
print("2. Loading LPS TTL + finding LPs for JM addresses...")
lp_addrs, lp_blocks, lp_prefixes = load_lps_ttl()
jm_addr_set = set(jm_addrs)
lp_ids = {lp for lp, addrs in lp_addrs.items() if addrs & jm_addr_set}
print(f"   Loaded {len(lp_addrs)} LPs; {len(lp_ids)} reference a JM address")

# Step 3: Stream beeldbank.csv — collect rows at our LPs + candidates for enrichment
print("3. Streaming beeldbank.csv...")
current_uris = set()
for lp in lp_ids:
    for a in lp_addrs[lp]:
        current_uris.add(f"{ADAMLINK_PREFIX}{a}")

MATCH_CAP = 15
CANDIDATE_CAP = 10

matched_bb = []
matched_keys = set()  # (resource, address) dedup
candidate_bb = []     # one row per novel adamlink address not at our LPs
candidate_addrs = set()

bb_header = None
scanned = 0
with open(f"{SRC}/beeldbank.csv", newline='') as f:
    reader = csv.DictReader(f)
    bb_header = reader.fieldnames
    for row in reader:
        scanned += 1
        addr = row.get('address', '').strip()
        if not addr or not addr.startswith(ADAMLINK_PREFIX):
            continue
        res = row.get('resource', '').strip()
        if not res:
            continue
        key = (res, addr)
        if addr in current_uris:
            if key not in matched_keys and len(matched_bb) < MATCH_CAP:
                matched_keys.add(key)
                matched_bb.append(row)
        elif addr not in candidate_addrs and len(candidate_bb) < CANDIDATE_CAP:
            candidate_addrs.add(addr)
            candidate_bb.append(row)
        if len(matched_bb) >= MATCH_CAP and len(candidate_bb) >= CANDIDATE_CAP:
            break
        if scanned % 500_000 == 0:
            print(f"   scanned {scanned:,} rows, matched {len(matched_bb)}, candidates {len(candidate_bb)}")

print(f"   Scanned {scanned:,} rows")
print(f"   Matched from JM-linked LPs: {len(matched_bb)}")

# Step 4: If few matches, enrich via candidate addresses (find the LPs that cover them)
unique_matches = len({r['resource'] for r in matched_bb})
if unique_matches < 3 and candidate_bb:
    take = min(5, len(candidate_bb))
    print(f"   Only {unique_matches} unique images — enriching with {take} candidate addresses")
    enrich_ids = {r['address'].replace(ADAMLINK_PREFIX, '') for r in candidate_bb[:take]}
    for lp, addrs in lp_addrs.items():
        if addrs & enrich_ids:
            lp_ids.add(lp)
    print(f"   LPs now: {len(lp_ids)}")
    matched_bb.extend(candidate_bb[:take])

bb_out = matched_bb

# Synthetic street-fallback row, kept in sync with the hand-maintained
# fixtures/seed-streets.ttl (which this script does not generate). Empty address +
# a street URI → exercises beeldbank's street fallback and the LINESTRING
# rasterisation path in the integration seed, which real address-resolved rows
# never reach. seedTestData ingests seed-streets.ttl before beeldbank.
bb_out.append({
    'resource': 'https://ams-migrate.memorix.io/resources/records/seed-street-feature-0001',
    'title': 'Seed Street Image',
    'thumbnail': 'https://images.memorix.nl/seed-thumb.jpg',
    'startDate': '1950-01-01',
    'endDate': '1950-12-31',
    'textDate': '1950',
    'address': '',
    'street': 'https://adamlink.nl/geo/street/seed-straat/1',
})

print(f"   Final beeldbank rows: {len(bb_out)}, unique images: {len({r['resource'] for r in bb_out})}")

# Step 5: in-scope addresses = union of the selected LPs' geoWithin addresses
print("4. Extracting LP + adressen blocks from the TTLs...")
all_addrs = set()
for lp in lp_ids:
    all_addrs |= lp_addrs[lp]

lps_ttl = extract_lps_ttl(lp_ids, lp_blocks, lp_prefixes)
adressen_ttl = extract_adressen_ttl(all_addrs)
print(f"   {len(lp_ids)} LPs, {len(all_addrs)} addresses")

# Write all fixtures
print("5. Writing fixtures...")
with open(f"{DST}/lps.ttl", 'w') as f:
    f.write(lps_ttl)
print(f"   lps.ttl: {lps_ttl.count(chr(10))+1} lines")

with open(f"{DST}/adressen.ttl", 'w') as f:
    f.write(adressen_ttl)
print(f"   adressen.ttl: {adressen_ttl.count(chr(10))+1} lines")

with open(f"{DST}/beeldbank.csv", 'w', newline='') as f:
    writer = csv.DictWriter(f, fieldnames=bb_header, quoting=csv.QUOTE_MINIMAL, extrasaction='ignore')
    writer.writeheader()
    for row in bb_out:
        writer.writerow(row)
print(f"   beeldbank.csv: {len(bb_out)+1} lines")

jm_header = list(jm_rows[0].keys())
with open(f"{DST}/jm.csv", 'w', newline='') as f:
    writer = csv.DictWriter(f, fieldnames=jm_header, quoting=csv.QUOTE_MINIMAL)
    writer.writeheader()
    for row in jm_rows:
        writer.writerow(row)
print(f"   jm.csv: {len(jm_rows)+1} lines")

# Summary
print("\n=== Summary ===")
print(f"LPs: {len(lp_ids)}")
print(f"Addresses: {len(all_addrs)}")
print(f"Beeldbank rows: {len(bb_out)}, unique images: {len({r['resource'] for r in bb_out})}")
print(f"JM persons: {len(jm_rows)}")
